import { UploadCloud, PackageCheck, QrCode } from "lucide-react";
import FadeIn from "../ui/FadeIn.jsx";
import GlassCard from "../ui/GlassCard.jsx";

const steps = [
  {
    number: "01",
    icon: QrCode,
    title: "Scan counter QR",
    description: "Locate and scan the QR code generated by the shop owner at their counter using your phone.",
  },
  {
    number: "02",
    icon: UploadCloud,
    title: "Drop files & preferences",
    description: "Upload your PDF, image, or document and select print settings instantly on your device.",
  },
  {
    number: "03",
    icon: PackageCheck,
    title: "Printed in seconds",
    description: "Your document is sent directly to the shopkeeper's dashboard. Pay and collect your prints.",
  },
];

export default function HowItWorks() {
  return (
    <section id="how-it-works" className="relative py-28 px-6">
      <div className="max-w-6xl mx-auto">
        <FadeIn className="max-w-xl">
          <h2 className="font-display text-4xl tracking-tight text-ink">How it works</h2>
          <p className="mt-4 text-ink-faint text-lg">
            Three steps between you and a finished print, start to finish.
          </p>
        </FadeIn>

        <div className="mt-16 grid md:grid-cols-3 gap-6">
          {steps.map((step, i) => (
            <FadeIn key={step.number} delay={i * 120}>
              <GlassCard hover className="p-8 h-full">
                <span className="font-display text-4xl text-accent-dim" style={{ WebkitTextStroke: "1.5px var(--color-accent)", color: "transparent" }}>
                  {step.number}
                </span>
                <div className="mt-5 grid place-items-center w-11 h-11 rounded-xl bg-accent-dim text-accent">
                  <step.icon size={20} />
                </div>
                <h3 className="mt-5 font-display text-xl text-ink">{step.title}</h3>
                <p className="mt-2 text-sm text-ink-faint leading-relaxed">{step.description}</p>
              </GlassCard>
            </FadeIn>
          ))}
        </div>
      </div>
    </section>
  );
}
